### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bugbounter**
Added bugbounter

### CODE REVIEW

**Comment by bugbounter** [comment]
waiting for the approval

**Comment by canengin29** [comment]
Hello, my manager (the user with the username "bugbounter") has added BugBounter (https://bugbounter.com) to the page in the following link: https://github.com/disclose/bug-bounty-platforms. Could you review the request, and get back to us? - Thank you in advance.

**Comment by yesnet0** [comment]
LGTM! Thank you!

**Comment by canengin29** [comment]
Thank you so much. Can Engincje ***@***.***> kirjoitti 7.09.2023 kello 11.12 ip.:﻿
Merged #32 into main.

**Pull request merged**
